name: calculator_app
description: "A sleek and interactive calculator app using Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Enhancements
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # State Management
  provider: ^6.0.5

  # Math Calculations
  math_expressions: ^2.0.0

  # Haptic Feedback (for next step)
  flutter_vibrate: ^1.3.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/  # For button press sounds

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
